/*
 * hla_engine.js
 * HLA allele-level and molecular (eplet) mismatch engine for the RAMRT calculator.
 *
 * Reference database: window.HLA_REF, generated by tools/build_hla_reference.py from
 *   - HLAMatchmaker v3.1 ABC_Antibody_Analysis_3.1.xlsb  (class I allele x eplet table, categories Abver / Ehi / Elo)
 *   - HLAMatchmaker v3.1 DRDQDP_Antibody_Analysis_3.1.xlsb (class II beta & alpha tables, categories AbV / AbInt / Inter / oth,
 *     Aver / othA; DRB3/4/5 and DQA1 linkage tables)
 *   - IE.xlsx (PGIMER immunogenic eplet reference catalogue)
 *
 * Data model (mirrors the workbooks): every allele is a list of "cells"; a cell is one polymorphic position
 * (workbook column) carrying one eplet name with the category the workbook assigns to that column.
 *
 * Methodology (HLAMatchmaker):
 *   * a donor cell is MISMATCHED when no allele of the recipient in the same class carries the same cell
 *     (class I: A+B+C pooled; class II beta: DRB1/3/4/5+DQB1+DPB1 pooled; class II alpha: DQA1+DPA1 pooled),
 *     i.e. intralocus and interlocus comparison column by column, as the workbook does;
 *   * the mismatch load is the number of unique mismatched eplet names;
 *   * antibody-verified (AbVer) eplets are those flagged in the workbooks; ElliPro high/low and interlocus/other
 *     categories are carried through unchanged (antibody-verified takes precedence when a name occurs in two cells);
 *   * "immunogenic" load = mismatched eplets whose name is in the IE.xlsx catalogue.
 * Allele-level mismatch: number of distinct donor alleles at a locus that the recipient does not carry
 * (0-2; a homozygous donor contributes at most one). The haplotype-count variant is also reported.
 *
 * Works in the browser (global HLAEngine) and in Node (module.exports) so the same code is unit-tested.
 */
(function (root, factory) {
    if (typeof module === 'object' && module.exports) module.exports = factory();
    else root.HLAEngine = factory();
})(typeof self !== 'undefined' ? self : this, function () {
    'use strict';

    const LOCI = ['A', 'B', 'C', 'DRB1', 'DRB3', 'DRB4', 'DRB5', 'DQA1', 'DQB1', 'DPA1', 'DPB1'];
    const CLASS_I = ['A', 'B', 'C'];
    const CLASS_II_B = ['DRB1', 'DRB3', 'DRB4', 'DRB5', 'DQB1', 'DPB1'];
    const CLASS_II_A = ['DQA1', 'DPA1'];
    const GROUP_OF = { A: 'ABC', B: 'ABC', C: 'ABC', DRB1: 'DR', DRB3: 'DR', DRB4: 'DR', DRB5: 'DR', DQA1: 'DQ', DQB1: 'DQ', DPA1: 'DP', DPB1: 'DP' };
    const LOCUS_ALIASES = {
        A: 'A', B: 'B', C: 'C', CW: 'C',
        DRB1: 'DRB1', DR: 'DRB1', DRB3: 'DRB3', DRB4: 'DRB4', DRB5: 'DRB5',
        DQA1: 'DQA1', DQA: 'DQA1', DQB1: 'DQB1', DQB: 'DQB1',
        DPA1: 'DPA1', DPA: 'DPA1', DPB1: 'DPB1', DPB: 'DPB1'
    };
    const CATEGORY_LABEL = {
        Abver: 'Antibody-verified', Ehi: 'ElliPro high (not Ab-verified)', Elo: 'ElliPro low (not Ab-verified)',
        AbV: 'Antibody-verified', AbInt: 'Antibody-verified interlocus', Inter: 'Interlocus (DR/DQ/DP shared)', oth: 'Other',
        Aver: 'Antibody-verified', othA: 'Other'
    };
    const ABVER_CATS = ['Abver', 'AbV', 'AbInt', 'Aver'];
    const DEFAULT_OPTIONS = { inferLinked: true, population: 'API', alleleRule: 'unique' };

    let REF = null;
    let DB = null;

    function setReference(ref) {
        REF = ref;
        DB = buildIndex(ref);
        return DB;
    }
    function getReference() { return REF; }

    function buildIndex(ref) {
        const groups = {};
        ['classI', 'classIIB', 'classIIA'].forEach(function (k) {
            const g = ref[k];
            groups[k] = {
                raw: g,
                cellName: g.cells.map(function (c) { return g.eplets[c[1]]; }),
                cellCat: g.cells.map(function (c) { return g.categories[c[2]]; }),
                cellCol: g.cells.map(function (c) { return c[0]; })
            };
        });
        const alleleGroup = {};
        const byPrefix = {};
        Object.keys(groups).forEach(function (k) {
            Object.keys(groups[k].raw.alleles).forEach(function (a) {
                alleleGroup[a] = k;
                const p = a.split(':')[0];
                (byPrefix[p] = byPrefix[p] || []).push(a);
            });
        });
        Object.keys(byPrefix).forEach(function (p) { byPrefix[p].sort(); });
        const ieI = {}, ieII = {};
        Object.keys(ref.ie.mapI).forEach(function (k) { if (ref.ie.mapI[k]) ieI[ref.ie.mapI[k]] = k; });
        Object.keys(ref.ie.mapII).forEach(function (k) { if (ref.ie.mapII[k]) ieII[ref.ie.mapII[k]] = k; });
        const drb345ByDrb1 = {};
        (ref.drb345 || []).forEach(function (r) { if (r.drb1) (drb345ByDrb1[r.drb1] = drb345ByDrb1[r.drb1] || []).push(r); });
        const dqaByDqb1 = {};
        (ref.dqa || []).forEach(function (r) { if (r.dqb1 && r.dqa1) (dqaByDqb1[r.dqb1] = dqaByDqb1[r.dqb1] || []).push(r); });
        return { groups: groups, alleleGroup: alleleGroup, byPrefix: byPrefix, ieI: ieI, ieII: ieII, drb345ByDrb1: drb345ByDrb1, dqaByDqb1: dqaByDqb1 };
    }

    function requireRef() {
        if (!REF || !DB) throw new Error('HLA reference database not loaded (call HLAEngine.setReference(window.HLA_REF))');
    }

    function pad2(s) { return s.length < 2 ? ('0' + s) : s; }
    function isAbver(cat) { return ABVER_CATS.indexOf(cat) !== -1; }

    /* ------------------------------------------------------------------ */
    /* Typing parser & validation                                          */
    /* ------------------------------------------------------------------ */
    function parseToken(raw) {
        const rec = { raw: raw, locus: null, allele: null, status: 'invalid', message: '', suggestions: [] };
        let t = raw.trim();
        t = t.replace(/\(.*?\)/g, '');                // A*24(9) -> A*24
        t = t.replace(/^["'\[\]]+|["'\[\]\.]+$/g, '');
        t = t.replace(/^HLA[-\s]?/i, '');
        t = t.replace(/::+/g, ':').replace(/\s+/g, '');
        const dup = t.match(/^([A-Za-z]+[1-5]?)\*([A-Za-z]+[1-5]?)\*(.+)$/);   // A*A*03:01:01:01 -> A*03:01:01:01 (locus prefix written twice)
        if (dup && dup[1].toUpperCase() === dup[2].toUpperCase()) t = dup[2] + '*' + dup[3];
        t = t.replace(/[:.](?:x{2,}|n{2,})$/i, '');            // A*33:xx, B*15.XX: second field not determined -> handled as low resolution
        const gm = t.match(/^(.*\d)([GP])$/i);                    // A*11:01:01G, A*11:01P: IMGT G / P group
        if (gm) { t = gm[1]; rec.group = gm[2].toUpperCase(); }
        if (!t) { rec.status = 'empty'; return rec; }
        if (/^(?:[A-Za-z]+[1-5]?\*?)?(NA|N\/A|NIL|NONE|NEG|NT|X+|-+)$/i.test(t) || /^[A-Za-z]+[1-5]?\*$/.test(t)) {
            rec.status = 'empty'; rec.message = 'No allele entered'; return rec;
        }

        let locusRaw = null, f1 = null, f2 = null, suffix = null;
        let m = t.match(/^([A-Za-z]+[1-5]?)[\*!:]?(\d{1,3}):(\d{1,3})(?::\d{1,3})*([NLSCAQ])?$/i);   // A*02:01, DRB1*15:01:01, A!26:01, DRB1:11:01
        if (m) { locusRaw = m[1]; f1 = m[2]; f2 = m[3]; suffix = m[4] || null; }
        if (!m) {
            m = t.match(/^([A-Za-z]+[1-5]?)\*(\d{4})([NLSCAQ])?$/i);                     // A*0201
            if (m) { locusRaw = m[1]; f1 = m[2].slice(0, 2); f2 = m[2].slice(2); suffix = m[3] || null; }
        }
        if (!m) {
            m = t.match(/^([A-Za-z]+[1-5]?)\*(\d{1,3})$/i);                                // DRB1*15 (low resolution)
            if (m) { locusRaw = m[1]; f1 = m[2]; }
        }
        if (!m) {
            m = t.match(/^([A-Za-z]+)(\d{1,2})$/i);                                        // A2, B35, DR15 (serological)
            if (m) { locusRaw = m[1]; f1 = m[2]; }
        }
        if (!m) {
            if (/^\d{1,3}(:\d{1,3})?$/.test(t)) { rec.message = 'Missing locus prefix (e.g. write A*' + t + ')'; }
            else if (t.indexOf('/') !== -1) {                      // DRB1*15:01/03, DRB1*03:01/08:01(?)
                rec.message = 'Ambiguous typing: the report gives more than one possibility (' + t.replace(/\*/, ' ') + '). Enter the resolved allele, or one line per possibility';
            }
            else rec.message = 'Unrecognised HLA format';
            return rec;
        }
        const locus = LOCUS_ALIASES[locusRaw.toUpperCase()];
        if (!locus) { rec.message = 'Unknown locus "' + locusRaw + '"'; return rec; }
        rec.locus = locus;
        f1 = pad2(String(parseInt(f1, 10)));
        if (f2 === null) {
            rec.status = 'lowres';
            rec.allele = locus + '*' + f1;
            rec.message = 'Low-resolution entry; a two-field allele is required for eplet analysis';
            rec.suggestions = (DB && DB.byPrefix[locus + '*' + f1]) ? DB.byPrefix[locus + '*' + f1].slice(0, 12) : [];
            return rec;
        }
        f2 = pad2(String(parseInt(f2, 10)));
        rec.allele = locus + '*' + f1 + ':' + f2;
        if (suffix && suffix.toUpperCase() === 'N') {
            rec.status = 'null';
            rec.message = 'Null allele (not expressed): excluded from eplet analysis';
            return rec;
        }
        if (DB && DB.alleleGroup[rec.allele]) {
            rec.status = 'ok';
        } else {
            rec.status = 'unsupported';
            rec.message = 'Allele not present in the HLAMatchmaker 3.1 tables: counted for allele-level mismatch only';
            rec.suggestions = (DB && DB.byPrefix[locus + '*' + f1]) ? DB.byPrefix[locus + '*' + f1].slice(0, 12) : [];
        }
        return rec;
    }

    function parseTyping(text) {
        const tokens = [];
        const perLocus = {};
        const warnings = [];
        String(text || '').split(/[,;\n\r\t]+/).forEach(function (piece) {
            piece.split(/\s+/).forEach(function (raw) {
                if (!raw.trim()) return;
                const rec = parseToken(raw);
                if (rec.status === 'empty') return;
                tokens.push(rec);
                if (!rec.locus) return;
                const L = perLocus[rec.locus] = perLocus[rec.locus] || { alleles: [], records: [] };
                if (rec.status === 'ok' || rec.status === 'unsupported') {
                    if (L.alleles.indexOf(rec.allele) === -1) {
                        if (L.alleles.length >= 2) {
                            rec.status = 'excess';
                            rec.message = 'More than two alleles entered for ' + rec.locus + '; "' + rec.raw + '" was ignored';
                        } else {
                            L.alleles.push(rec.allele);
                        }
                    } else {
                        rec.status = 'duplicate';
                        rec.message = 'Repeated allele (homozygous)';
                        L.homozygousEntered = true;
                    }
                }
                L.records.push(rec);
            });
        });
        const alleles = {};
        LOCI.forEach(function (locus) {
            const L = perLocus[locus];
            if (!L) return;
            const list = L.records.filter(function (r) { return r.status === 'ok' || r.status === 'unsupported'; })
                .map(function (r) { return { name: r.allele, locus: locus, inDb: r.status === 'ok', inferred: false }; });
            if (list.length) {
                if (list.length === 1) {
                    list[0].homozygous = true;
                    if (!L.homozygousEntered) warnings.push({ level: 'info', locus: locus, message: locus + ': single allele entered (' + list[0].name + ') and treated as homozygous' });
                }
                alleles[locus] = list;
            }
            L.records.forEach(function (r) {
                if (r.status === 'lowres') warnings.push({ level: 'error', locus: locus, message: locus + ': "' + r.raw + '" is low resolution' + (r.suggestions.length ? ' (candidates: ' + r.suggestions.slice(0, 6).join(', ') + (r.suggestions.length > 6 ? ', ...' : '') + ')' : '') });
                if (r.status === 'unsupported') warnings.push({ level: 'warn', locus: locus, message: locus + ': ' + r.allele + ' is not in the HLAMatchmaker 3.1 tables; it counts for allele-level mismatch but not for eplet analysis' + (r.suggestions.length ? ' (closest listed: ' + r.suggestions.slice(0, 6).join(', ') + ')' : '') });
                if (r.status === 'null') warnings.push({ level: 'warn', locus: locus, message: locus + ': ' + r.allele + 'N is a null allele and is excluded' });
                if (r.status === 'excess') warnings.push({ level: 'error', locus: locus, message: r.message });
                if (r.group && r.allele) warnings.push({ level: 'info', locus: locus, message: locus + ': "' + r.raw + '" is an IMGT ' + r.group + ' group; read as ' + r.allele + ' (members of the group share the sequence that carries the eplets)' });
            });
        });
        tokens.forEach(function (r) {
            if (r.status === 'invalid') warnings.push({ level: 'error', locus: r.locus, message: '"' + r.raw + '": ' + r.message });
        });
        return { tokens: tokens, alleles: alleles, warnings: warnings };
    }

    /* ------------------------------------------------------------------ */
    /* Linkage inference (DRB3/4/5 from DRB1; DQA1 from DRB1+DQB1)          */
    /* ------------------------------------------------------------------ */
    function inferLinked(person, options, notes, who) {
        const pop = options.population || 'API';
        const out = { drb345: [], dqa1: [] };
        const drb1 = (person.alleles.DRB1 || []).map(function (a) { return a.name; });
        const dqb1 = (person.alleles.DQB1 || []).map(function (a) { return a.name; });
        const hasDRB345 = ['DRB3', 'DRB4', 'DRB5'].some(function (l) { return person.alleles[l]; });
        if (drb1.length && !hasDRB345) {
            const chosen = {};
            drb1.forEach(function (d) {
                const rows = DB.drb345ByDrb1[d] || [];
                if (!rows.length) { notes.push({ level: 'warn', message: who + ': no DRB3/4/5 linkage data for ' + d + ' in the workbook table; DRB3/4/5 not inferred' }); return; }
                let cands = rows.filter(function (r) { return dqb1.length && r.dqb1 && dqb1.indexOf(r.dqb1) !== -1; });
                if (!cands.length) cands = rows;
                const best = cands.reduce(function (a, b) { return ((b.prop[pop] || 0) > (a.prop[pop] || 0)) ? b : a; });
                const label = best.drb345 ? best.drb345 : 'no DRB3/4/5 (NEG)';
                notes.push({ level: 'info', message: who + ': ' + d + ' -> ' + label + ' inferred from the DRB345DQB linkage table (code ' + best.drb345_code + ', proportion ' + Math.round((best.prop[pop] || 0) * 100) + '% in ' + pop + (best.dqb1 && dqb1.indexOf(best.dqb1) !== -1 ? ', consistent with ' + best.dqb1 : '') + ')' });
                if (best.drb345 && !chosen[best.drb345]) { chosen[best.drb345] = true; out.drb345.push({ name: best.drb345, locus: best.drb345.split('*')[0], inDb: !!DB.alleleGroup[best.drb345], inferred: true, from: d }); }
            });
        }
        if (dqb1.length && !person.alleles.DQA1) {
            const chosen = {};
            dqb1.forEach(function (b) {
                const rows = DB.dqaByDqb1[b] || [];
                if (!rows.length) { notes.push({ level: 'warn', message: who + ': no DQA1 linkage data for ' + b + '; DQA1 not inferred' }); return; }
                let cands = rows.filter(function (r) { return drb1.indexOf(r.drb1) !== -1; });
                let basis = 'DRB1-DQB1 haplotype';
                if (!cands.length) { cands = rows; basis = 'DQB1 only (DRB1 haplotype not listed)'; }
                const best = cands.reduce(function (a, c) { return (c.rank > a.rank) ? c : a; });
                notes.push({ level: 'info', message: who + ': ' + b + ' -> ' + best.dqa1 + ' inferred from the DQAB linkage table (' + (best.freq || 'frequency not stated') + ', ' + basis + (best.dqa1_code !== best.dqa1.replace(':', '') ? ', code ' + best.dqa1_code : '') + ')' });
                if (!chosen[best.dqa1]) { chosen[best.dqa1] = true; out.dqa1.push({ name: best.dqa1, locus: 'DQA1', inDb: !!DB.alleleGroup[best.dqa1], inferred: true, from: b }); }
            });
        }
        return out;
    }

    /* ------------------------------------------------------------------ */
    /* Core analysis                                                       */
    /* ------------------------------------------------------------------ */
    function firstField(a) { return a.split('*')[1].split(':')[0]; }

    /* Allele-level (two-field) and antigen-level (first-field) mismatch per locus.
       The thesis HLA registers and the Phase 4 risk model count mismatches at the antigen (first-field) level:
       97.9% of the recorded MM values in Dataset/Objective 1.xlsx follow that rule versus 87.0% for two-field counting. */
    function alleleLevel(recipient, donor, rule) {
        const perLocus = {};
        const evaluated = [];
        LOCI.forEach(function (locus) {
            const r = recipient.alleles[locus], d = donor.alleles[locus];
            if (!r || !d) return;
            const rn = r.map(function (a) { return a.name; }), dn = d.map(function (a) { return a.name; });
            const mismatched = dn.filter(function (a) { return rn.indexOf(a) === -1; });
            const hapList = dn.length === 1 ? [dn[0], dn[0]] : dn;
            const hapCount = hapList.filter(function (a) { return rn.indexOf(a) === -1; }).length;
            const matched = dn.filter(function (a) { return rn.indexOf(a) !== -1; });
            const rf = rn.map(firstField);
            const antigenGroups = [];
            dn.forEach(function (a) { const f = firstField(a); if (rf.indexOf(f) === -1 && antigenGroups.indexOf(f) === -1) antigenGroups.push(f); });
            const antigenMismatched = dn.filter(function (a) { return antigenGroups.indexOf(firstField(a)) !== -1; });
            perLocus[locus] = {
                locus: locus, group: GROUP_OF[locus], recipient: rn, donor: dn, mismatched: mismatched, matched: matched,
                count: rule === 'haplotype' ? hapCount : mismatched.length, countUnique: mismatched.length, countHaplotype: hapCount,
                antigenMismatched: antigenMismatched, antigenGroups: antigenGroups.map(function (f) { return locus + '*' + f; }), countAntigen: antigenGroups.length,
                correspondingRecipient: rn.filter(function (a) { return dn.indexOf(a) === -1; }),
                inferred: (r.some(function (a) { return a.inferred; }) || d.some(function (a) { return a.inferred; }))
            };
            evaluated.push(locus);
        });
        function sum(loci, key) { return loci.reduce(function (s, l) { return s + (perLocus[l] ? perLocus[l][key] : 0); }, 0); }
        function all(loci) { return loci.every(function (l) { return perLocus[l]; }); }
        return {
            perLocus: perLocus, evaluated: evaluated,
            totalABDR: all(['A', 'B', 'DRB1']) ? sum(['A', 'B', 'DRB1'], 'count') : null,
            totalABDRDQ: all(['A', 'B', 'DRB1', 'DQB1']) ? sum(['A', 'B', 'DRB1', 'DQB1'], 'count') : null,
            totalAll: sum(evaluated, 'count'),
            totalABDRAntigen: all(['A', 'B', 'DRB1']) ? sum(['A', 'B', 'DRB1'], 'countAntigen') : null,
            totalABDRDQAntigen: all(['A', 'B', 'DRB1', 'DQB1']) ? sum(['A', 'B', 'DRB1', 'DQB1'], 'countAntigen') : null,
            totalAllAntigen: sum(evaluated, 'countAntigen'),
            mismatchedAlleles: evaluated.reduce(function (acc, l) { return acc.concat(perLocus[l].mismatched.map(function (a) { return { locus: l, donor: a, recipient: perLocus[l].recipient }; })); }, [])
        };
    }

    function locusKey(l) { return (l === 'DRB3' || l === 'DRB4' || l === 'DRB5') ? 'DRB345' : l; }

    function epletMismatch(groupKey, loci, recipient, donor, ieMap, warnings, classLabel) {
        const g = DB.groups[groupKey];
        const recAlleles = [], donAlleles = [];
        loci.forEach(function (l) {
            (recipient.alleles[l] || []).forEach(function (a) { if (a.inDb) recAlleles.push(a); });
            (donor.alleles[l] || []).forEach(function (a) { if (a.inDb) donAlleles.push(a); });
        });
        const res = { classLabel: classLabel, evaluated: false, recipientAlleles: recAlleles.map(function (a) { return a.name; }), donorAlleles: [], repertoireSize: 0,
                      mismatched: [], total: 0, abver: 0, ie: 0, nonIE: 0, byCategory: {}, byLocus: {}, byGroup: {}, skippedDonorLoci: [] };
        if (!recAlleles.length || !donAlleles.length) return res;
        // donor loci that the recipient has not typed cannot be evaluated fairly -> skipped with a warning
        const recKeys = {};
        recAlleles.forEach(function (a) { recKeys[locusKey(a.locus)] = true; });
        const usableDonor = donAlleles.filter(function (a) {
            if (!recKeys[locusKey(a.locus)]) { if (res.skippedDonorLoci.indexOf(a.locus) === -1) res.skippedDonorLoci.push(a.locus); return false; }
            return true;
        });
        if (res.skippedDonorLoci.length) warnings.push({ level: 'warn', message: classLabel + ': donor ' + res.skippedDonorLoci.join('/') + ' allele(s) skipped because the recipient has no typing for that locus; enter the recipient typing to evaluate them' });
        if (!usableDonor.length) return res;

        const repertoire = {};
        recAlleles.forEach(function (a) { g.raw.alleles[a.name].forEach(function (i) { repertoire[i] = true; }); });
        res.repertoireSize = Object.keys(repertoire).length;
        const mmMap = {};
        usableDonor.forEach(function (a) {
            const perName = {};
            g.raw.alleles[a.name].forEach(function (i) {
                if (repertoire[i]) return;
                const name = g.cellName[i], cat = g.cellCat[i];
                const cur = perName[name];
                if (!cur || (isAbver(cat) && !isAbver(cur.category))) perName[name] = { name: name, category: cat };
            });
            const list = Object.keys(perName).map(function (n) {
                const e = perName[n];
                return { name: e.name, category: e.category, categoryLabel: CATEGORY_LABEL[e.category] || e.category, abver: isAbver(e.category), ie: !!ieMap[e.name], ieName: ieMap[e.name] || null };
            }).sort(sortEplets);
            list.forEach(function (e) {
                const m = mmMap[e.name];
                if (!m) mmMap[e.name] = { name: e.name, category: e.category, categoryLabel: e.categoryLabel, abver: e.abver, ie: e.ie, ieName: e.ieName, donorAlleles: [a.name], loci: [a.locus] };
                else {
                    if (e.abver && !m.abver) { m.abver = true; m.category = e.category; m.categoryLabel = e.categoryLabel; }
                    m.donorAlleles.push(a.name);
                    if (m.loci.indexOf(a.locus) === -1) m.loci.push(a.locus);
                }
            });
            res.donorAlleles.push({ allele: a.name, locus: a.locus, inferred: !!a.inferred, epletCount: g.raw.colCount[a.name], mismatched: list, count: list.length, abver: list.filter(function (e) { return e.abver; }).length, ie: list.filter(function (e) { return e.ie; }).length });
        });
        res.evaluated = true;
        res.mismatched = Object.keys(mmMap).map(function (k) { return mmMap[k]; }).sort(sortEplets);
        res.total = res.mismatched.length;
        res.abver = res.mismatched.filter(function (e) { return e.abver; }).length;
        res.ie = res.mismatched.filter(function (e) { return e.ie; }).length;
        res.nonIE = res.total - res.ie;
        res.mismatched.forEach(function (e) {
            res.byCategory[e.category] = (res.byCategory[e.category] || 0) + 1;
            e.loci.forEach(function (l) {
                const L = res.byLocus[l] = res.byLocus[l] || { locus: l, total: 0, abver: 0, ie: 0 };
                L.total++; if (e.abver) L.abver++; if (e.ie) L.ie++;
                const G = res.byGroup[GROUP_OF[l]] = res.byGroup[GROUP_OF[l]] || { group: GROUP_OF[l], total: 0, abver: 0, ie: 0, _names: {} };
                if (!G._names[e.name]) { G._names[e.name] = true; G.total++; if (e.abver) G.abver++; if (e.ie) G.ie++; }
            });
        });
        Object.keys(res.byGroup).forEach(function (k) { delete res.byGroup[k]._names; });
        return res;
    }

    function sortEplets(a, b) {
        const na = parseInt(a.name.replace(/^[a-z]+/, ''), 10), nb = parseInt(b.name.replace(/^[a-z]+/, ''), 10);
        if (!isNaN(na) && !isNaN(nb) && na !== nb) return na - nb;
        return a.name < b.name ? -1 : (a.name > b.name ? 1 : 0);
    }

    function hashString(s) {
        let h = 5381;
        for (let i = 0; i < s.length; i++) h = ((h << 5) + h + s.charCodeAt(i)) | 0;
        return ('00000000' + (h >>> 0).toString(16)).slice(-8);
    }

    function analyze(recipientText, donorText, opts) {
        requireRef();
        const options = Object.assign({}, DEFAULT_OPTIONS, opts || {});
        const recipient = parseTyping(recipientText);
        const donor = parseTyping(donorText);
        const warnings = [];
        recipient.warnings.forEach(function (w) { warnings.push(Object.assign({ side: 'Recipient' }, w, { message: 'Recipient ' + w.message })); });
        donor.warnings.forEach(function (w) { warnings.push(Object.assign({ side: 'Donor' }, w, { message: 'Donor ' + w.message })); });

        const inferred = { recipient: { drb345: [], dqa1: [] }, donor: { drb345: [], dqa1: [] }, notes: [] };
        if (options.inferLinked) {
            inferred.recipient = inferLinked(recipient, options, inferred.notes, 'Recipient');
            inferred.donor = inferLinked(donor, options, inferred.notes, 'Donor');
            [[recipient, inferred.recipient], [donor, inferred.donor]].forEach(function (pair) {
                pair[1].drb345.forEach(function (a) { (pair[0].alleles[a.locus] = pair[0].alleles[a.locus] || []).push(a); });
                pair[1].dqa1.forEach(function (a) { (pair[0].alleles.DQA1 = pair[0].alleles.DQA1 || []).push(a); });
            });
        }

        const allele = alleleLevel(recipient, donor, options.alleleRule);
        const classI = epletMismatch('classI', CLASS_I, recipient, donor, DB.ieI, warnings, 'Class I (HLA-A/B/C)');
        const classIIB = epletMismatch('classIIB', CLASS_II_B, recipient, donor, DB.ieII, warnings, 'Class II beta chains (DRB1/3/4/5, DQB1, DPB1)');
        const classIIA = epletMismatch('classIIA', CLASS_II_A, recipient, donor, DB.ieII, warnings, 'Class II alpha chains (DQA1, DPA1)');

        // completeness advisories (HLAMatchmaker assumes complete typing per class)
        function typed(p, l) { return !!(p.alleles[l] && p.alleles[l].length); }
        if ((typed(recipient, 'A') || typed(recipient, 'B')) && !typed(recipient, 'C') && !typed(donor, 'C'))
            warnings.push({ level: 'info', message: 'HLA-C not typed for either person: class I eplet load computed on A and B only (HLAMatchmaker assumes complete A/B/C typing)' });
        if (typed(recipient, 'DRB1') && !typed(recipient, 'DPB1') && !typed(donor, 'DPB1'))
            warnings.push({ level: 'info', message: 'HLA-DP not typed: DP eplets are not included' });
        if (!options.inferLinked && typed(recipient, 'DRB1') && !['DRB3', 'DRB4', 'DRB5'].some(function (l) { return typed(recipient, l) || typed(donor, l); }))
            warnings.push({ level: 'info', message: 'DRB3/4/5 not typed and linkage inference is off: DRB3/4/5 eplets are not included' });
        if (!options.inferLinked && typed(recipient, 'DQB1') && !typed(recipient, 'DQA1') && !typed(donor, 'DQA1'))
            warnings.push({ level: 'info', message: 'DQA1 not typed and linkage inference is off: DQA1 eplets are not included' });

        const classII = combine([classIIB, classIIA]);
        const overall = combine([classI, classIIB, classIIA]);
        const immunogenic = overall.list.filter(function (e) { return e.ie; });

        const evaluable = allele.evaluated.length > 0 || classI.evaluated || classIIB.evaluated || classIIA.evaluated;
        const sig = hashString(JSON.stringify([normalizedList(recipient), normalizedList(donor), options.inferLinked, options.population, options.alleleRule, REF.meta.built]));
        return {
            options: options, recipient: recipient, donor: donor, inferred: inferred,
            allele: allele, eplet: { classI: classI, classIIB: classIIB, classIIA: classIIA, classII: classII, overall: overall },
            immunogenic: immunogenic, warnings: warnings.concat(inferred.notes), evaluable: evaluable, signature: sig,
            reference: { built: REF.meta.built, sources: REF.meta.sources }
        };
    }

    function normalizedList(p) {
        const out = {};
        LOCI.forEach(function (l) { if (p.alleles[l]) out[l] = p.alleles[l].map(function (a) { return a.name + (a.inferred ? '*inf' : ''); }).sort(); });
        return out;
    }

    function combine(parts) {
        const map = {};
        parts.forEach(function (p) { p.mismatched.forEach(function (e) { if (!map[e.name + '|' + p.classLabel]) map[e.name + '|' + p.classLabel] = Object.assign({ classLabel: p.classLabel }, e); }); });
        const list = Object.keys(map).map(function (k) { return map[k]; });
        return {
            evaluated: parts.some(function (p) { return p.evaluated; }),
            list: list, total: list.length,
            abver: list.filter(function (e) { return e.abver; }).length,
            ie: list.filter(function (e) { return e.ie; }).length,
            nonIE: list.filter(function (e) { return !e.ie; }).length
        };
    }

    /* ------------------------------------------------------------------ */
    /* Plain-text export                                                   */
    /* ------------------------------------------------------------------ */
    function formatReport(res) {
        const L = [];
        L.push('RAMRT HLA mismatch & eplet report  (result ID ' + res.signature + ')');
        L.push('Reference: ' + res.reference.sources.join('; ') + ' [built ' + res.reference.built + ']');
        L.push('');
        L.push('ALLELE-LEVEL (two-field) AND ANTIGEN-LEVEL (first-field) MISMATCH');
        res.allele.evaluated.forEach(function (l) {
            const p = res.allele.perLocus[l];
            L.push('  ' + l + ': donor ' + p.donor.join('/') + ' vs recipient ' + p.recipient.join('/') + ' -> allele MM ' + p.count + (p.mismatched.length ? ' (' + p.mismatched.join(', ') + ')' : '') + ', antigen MM ' + p.countAntigen + (p.inferred ? ' [inferred allele involved]' : ''));
        });
        L.push('  Allele-level totals: A+B+DRB1 ' + (res.allele.totalABDR === null ? 'n/a' : res.allele.totalABDR) + ' | A+B+DRB1+DQB1 ' + (res.allele.totalABDRDQ === null ? 'n/a' : res.allele.totalABDRDQ) + ' | all evaluated loci ' + res.allele.totalAll);
        L.push('  Antigen-level totals (thesis / risk-model convention): A+B+DRB1 ' + (res.allele.totalABDRAntigen === null ? 'n/a' : res.allele.totalABDRAntigen) + ' | A+B+DRB1+DQB1 ' + (res.allele.totalABDRDQAntigen === null ? 'n/a' : res.allele.totalABDRDQAntigen) + ' | all evaluated loci ' + res.allele.totalAllAntigen);
        L.push('');
        ['classI', 'classIIB', 'classIIA'].forEach(function (k) {
            const c = res.eplet[k];
            L.push('EPLET MISMATCH - ' + c.classLabel + (c.evaluated ? '' : ' (not evaluated)'));
            if (!c.evaluated) return;
            L.push('  total ' + c.total + ' | antibody-verified ' + c.abver + ' | IE-catalogue immunogenic ' + c.ie + ' | non-immunogenic ' + c.nonIE);
            c.donorAlleles.forEach(function (d) { L.push('  ' + d.allele + (d.inferred ? ' (inferred)' : '') + ': ' + d.count + ' mismatched eplets [' + d.mismatched.map(function (e) { return e.name + (e.ie ? '*' : ''); }).join(', ') + ']'); });
        });
        L.push('');
        L.push('IMMUNOGENIC (IE.xlsx) MISMATCHED EPLETS: ' + (res.immunogenic.length ? res.immunogenic.map(function (e) { return e.name; }).join(', ') : 'none'));
        L.push('OVERALL: total ' + res.eplet.overall.total + ' | immunogenic ' + res.eplet.overall.ie + ' | non-immunogenic ' + res.eplet.overall.nonIE + ' | antibody-verified ' + res.eplet.overall.abver);
        if (res.warnings.length) { L.push(''); L.push('NOTES'); res.warnings.forEach(function (w) { L.push('  [' + w.level + '] ' + w.message); }); }
        return L.join('\n');
    }

    /* ------------------------------------------------------------------ */
    /* Self-test (validation vectors generated by tools/build_hla_reference.py) */
    /* ------------------------------------------------------------------ */
    function selfTest(vectors) {
        requireRef();
        const results = [];
        let pass = 0, fail = 0;
        (vectors.perAllele || []).forEach(function (v) {
            const gk = DB.alleleGroup[v.allele];
            const g = gk ? DB.groups[gk] : null;
            if (!g) { results.push({ test: 'Per-allele eplet counts ' + v.allele, ok: false, detail: 'not in database' }); fail++; return; }
            const ids = g.raw.alleles[v.allele];
            const cats = ids.map(function (i) { return g.cellCat[i]; });
            let ok, detail;
            if (v.tot !== undefined) {
                const mine = { tot: ids.length, abver: cats.filter(function (c) { return c === 'Abver'; }).length, ehi: cats.filter(function (c) { return c === 'Ehi'; }).length, elo: cats.filter(function (c) { return c === 'Elo'; }).length };
                ok = mine.tot === v.tot && mine.abver === v.abver && mine.ehi === v.ehi && mine.elo === v.elo;
                detail = 'workbook ' + v.tot + ' eplet cells (' + v.abver + ' AbVer / ' + v.ehi + ' ElliPro-high / ' + v.elo + ' ElliPro-low) vs engine ' + mine.tot + ' (' + mine.abver + ' / ' + mine.ehi + ' / ' + mine.elo + ')';
            } else {
                const mine = { abver: cats.filter(isAbver).length, other: cats.filter(function (c) { return !isAbver(c); }).length };
                ok = (ids.length === v.abver + v.other && mine.abver === v.abver) || (g.raw.colCount[v.allele] === v.abver + v.other && mine.abver === v.abver);
                detail = 'workbook ' + v.abver + ' AbVer + ' + v.other + ' other vs engine ' + mine.abver + ' + ' + mine.other;
            }
            results.push({ test: 'Per-allele eplet counts ' + v.allele, ok: ok, detail: detail });
            ok ? pass++ : fail++;
        });
        (vectors.pairs || []).forEach(function (v, idx) {
            const rt = Object.keys(v.recipient).map(function (l) { return v.recipient[l].join(', '); }).join(', ');
            const dt = Object.keys(v.donor).map(function (l) { return v.donor[l].join(', '); }).join(', ');
            const r1 = analyze(rt, dt, { inferLinked: false });
            const r2 = analyze(rt, dt, { inferLinked: false });
            const detail = Object.keys(v.expectedMM).map(function (l) { return l + ' ' + (r1.allele.perLocus[l] ? r1.allele.perLocus[l].countAntigen : '?') + '/' + v.expectedMM[l]; }).join(', ');
            const ok = Object.keys(v.expectedMM).every(function (l) { return r1.allele.perLocus[l] && r1.allele.perLocus[l].countAntigen === v.expectedMM[l] && r1.allele.perLocus[l].countUnique >= r1.allele.perLocus[l].countAntigen; });
            results.push({ test: 'Antigen-level MM vs thesis record #' + (idx + 1), ok: ok, detail: 'engine/recorded: ' + detail });
            ok ? pass++ : fail++;
            const det = r1.signature === r2.signature && JSON.stringify(r1.eplet.overall) === JSON.stringify(r2.eplet.overall);
            results.push({ test: 'Reproducibility (repeat run) #' + (idx + 1), ok: det, detail: 'result ID ' + r1.signature + ', eplet MM ' + r1.eplet.overall.total + ' (IE ' + r1.eplet.overall.ie + ')' });
            det ? pass++ : fail++;
        });
        return { pass: pass, fail: fail, results: results };
    }

    return {
        LOCI: LOCI, CLASS_I: CLASS_I, CLASS_II_B: CLASS_II_B, CLASS_II_A: CLASS_II_A, GROUP_OF: GROUP_OF, CATEGORY_LABEL: CATEGORY_LABEL,
        setReference: setReference, getReference: getReference, parseToken: parseToken, parseTyping: parseTyping,
        analyze: analyze, formatReport: formatReport, selfTest: selfTest, DEFAULT_OPTIONS: DEFAULT_OPTIONS
    };
});
