"""
fetch_structures.py — offline packaging for the 3D eplet view.

1. Downloads the verified RCSB PDB entries used by hla_3d.js into structures/rcsb/<ID>.pdb.
2. Writes ../hla_structures_data.js (window.HLA_STRUCTURES) with the HLA chains + peptide of each entry
   trimmed to ATOM records, so the viewer works from file:// without network access.
3. Downloads 3Dmol-min.js (pinned version) into ../vendor/ for offline use (cdnjs is the fallback).
4. Optionally (--phla3d <file with allele list>) downloads pHLA3D homology models into structures/phla3d/
   using the URL pattern configured below — respect their research-use licence and cite their papers.

Run from the clinical_risk_calculator folder:  python tools/fetch_structures.py
"""
import os, sys, json, time, io, urllib.request, re

HERE = os.path.dirname(os.path.abspath(__file__))
APP = os.path.abspath(os.path.join(HERE, '..'))
RCSB_DIR = os.path.join(APP, 'structures', 'rcsb')
PHLA_DIR = os.path.join(APP, 'structures', 'phla3d')
VENDOR = os.path.join(APP, 'vendor')
LIB_URL = 'https://cdnjs.cloudflare.com/ajax/libs/3Dmol/2.5.5/3Dmol-min.js'

# entry -> chains to keep (HLA chains + peptide; b2m/TCR/CD8 dropped). Matches hla_3d.js STRUCTURES.
ENTRIES = {
    '1AKJ': ['A', 'C'], '2BCK': ['A', 'C'], '1Q94': ['A', 'C'], '1A1N': ['A', 'C'], '1M6O': ['A', 'C'],
    '2RFX': ['A', 'C'], '1HSA': ['A', 'C'], '1MI5': ['A', 'C'], '5EO0': ['A', 'C'], '1QQD': ['A', 'C'],
    '5W67': ['A', 'C'],
    '1DLH': ['A', 'B', 'C'], '1BX2': ['A', 'B', 'C'], '1J8H': ['A', 'B', 'C'], '1A6A': ['A', 'B', 'C'],
    '1JK8': ['A', 'B', 'C'], '1S9V': ['A', 'B', 'C'], '1UVQ': ['A', 'B', 'C'], '3LQZ': ['A', 'B', 'C']
}

def get(url, binary=False, retries=3):
    for i in range(retries):
        try:
            req = urllib.request.Request(url, headers={'User-Agent': 'RAMRT-calculator/1.0 (research use)'})
            with urllib.request.urlopen(req, timeout=60) as r:
                data = r.read()
            return data if binary else data.decode('utf-8', 'replace')
        except Exception as e:
            if i == retries - 1: raise
            time.sleep(2 * (i + 1))

def chain_lengths(pdb_text):
    seen = {}
    for line in pdb_text.splitlines():
        if line.startswith('ATOM') and line[12:16].strip() == 'CA':
            seen.setdefault(line[21], set()).add(line[22:27])
    return {c: len(v) for c, v in seen.items()}

def trim(pdb_text, keep):
    """Keep ATOM/HETATM lines of the wanted chains (first model only); every chain <= 20 residues is a peptide and is kept too."""
    lens = chain_lengths(pdb_text)
    wanted = set(keep) | {c for c, n in lens.items() if n <= 20}
    out = []
    for line in pdb_text.splitlines():
        if line.startswith('ENDMDL'): break
        if line.startswith(('ATOM', 'HETATM')) and line[21] in wanted and line[17:20] != 'HOH':
            out.append(line)
    out.append('END')
    return '\n'.join(out) + '\n', {c: lens.get(c, 0) for c in sorted(wanted)}

def main():
    os.makedirs(RCSB_DIR, exist_ok=True); os.makedirs(VENDOR, exist_ok=True)
    bundle = {}
    for pid, keep in ENTRIES.items():
        path = os.path.join(RCSB_DIR, pid + '.pdb')
        if not os.path.exists(path):
            print('downloading', pid); io.open(path, 'w', encoding='utf-8').write(get('https://files.rcsb.org/download/%s.pdb' % pid)); time.sleep(0.5)
        text = io.open(path, encoding='utf-8').read()
        trimmed, lens = trim(text, keep)
        bundle[pid] = {'chains': lens, 'pdb': trimmed}
        print('%s: kept chains %s, %d KB' % (pid, lens, len(trimmed) // 1024))
    js = os.path.join(APP, 'hla_structures_data.js')
    with io.open(js, 'w', encoding='utf-8') as f:
        f.write('/* GENERATED by tools/fetch_structures.py - trimmed RCSB PDB entries (HLA chains + peptide) for the offline 3D eplet view. Source: RCSB Protein Data Bank (https://www.rcsb.org). */\n')
        f.write('window.HLA_STRUCTURES = ')
        json.dump(bundle, f, separators=(',', ':'))
        f.write(';\n')
    print('wrote', os.path.relpath(js, APP), os.path.getsize(js) // 1024, 'KB')
    lib = os.path.join(VENDOR, '3Dmol-min.js')
    if not os.path.exists(lib):
        print('downloading 3Dmol 2.5.5'); io.open(lib, 'wb').write(get(LIB_URL, binary=True))
    print('vendor/3Dmol-min.js', os.path.getsize(lib) // 1024, 'KB')

    if '--phla3d' in sys.argv:
        # URL pattern must be set once known; kept explicit so nothing is fetched blindly.
        pattern = os.environ.get('PHLA3D_URL_PATTERN')   # e.g. https://www.phla3d.com.br/download/{allele_file}.pdb
        listing = sys.argv[sys.argv.index('--phla3d') + 1]
        if not pattern:
            print('Set PHLA3D_URL_PATTERN to the per-allele PDB URL pattern (with {allele}) before using --phla3d'); return
        os.makedirs(PHLA_DIR, exist_ok=True)
        manifest = {}
        for allele in [l.strip() for l in io.open(listing, encoding='utf-8') if l.strip()]:
            fname = allele.replace('*', '_').replace(':', '_') + '.pdb'
            dest = os.path.join(PHLA_DIR, fname)
            if not os.path.exists(dest):
                try:
                    io.open(dest, 'w', encoding='utf-8').write(get(pattern.format(allele=allele))); time.sleep(1.5)
                    print('pHLA3D model saved', allele)
                except Exception as e:
                    print('pHLA3D model not available for', allele, e); continue
            manifest[allele] = 'structures/phla3d/' + fname
        json.dump(manifest, io.open(os.path.join(PHLA_DIR, 'manifest.json'), 'w', encoding='utf-8'), indent=1)
        print('pHLA3D manifest:', len(manifest), 'models')

if __name__ == '__main__':
    main()
